name: Lint

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    branches:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install tox
        run: pip install "tox < 4"
      - name: Run black
        run: tox -e black
      - name: Run flake8
        run: tox -e flake8
      - name: Run mypy
        run: tox -e mypy
      - name: Check spelling
        run: tox -e codespell
      - name: Install requirements to generate docs
        run: sudo apt-get install -y libgeos-dev
      - name: Check documentation
        run: tox -e docs
